name: smash
version: 1.1
description: "The plugin for Super Smash Bros but in Minecraft."
author: "ClientDNS"
main: "de.clientdns.smash.SmashPlugin"
api-version: 1.19

commands:
  config:
    description: "Manages the config file."
  setup:
    description: "Setup a map."