name: smash
version: 1.0
description: "The plugin for Super Smash Bros but in Minecraft."
author: "ClientDNS"
main: "de.clientdns.smash.SmashPlugin"
api-version: 1.19

commands:
  config:
    description: "Manage the config."
  setup:
    description: "Setup a map."
