name: smash
version: 1.0
description: "The plugin for Super Smash Bros but in Minecraft."
author: "ClientDNS"
website: "https://github.com/ClientDNS/Smash"
main: "de.clientdns.smash.SmashPlugin"
api-version: 1.19
