name: smash
version: 1.0-SNAPSHOT
description: "The plugin for Super Smash Bros but in Minecraft."
author: "ClientDNS"
main: "de.clientdns.smash.SmashPlugin"
api-version: 1.19

commands:
  setup:
    description: "Setup a map."