name: Continuous Integration
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        java: [ 17 ]
    #      fail-fast: true
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: gradle/wrapper-validation-action@v1.1.0
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: 17 # ${{ matrix.java }}
          distribution: 'adopt'
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
