name: Continuous Integration
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 18 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: gradle/wrapper-validation-action@v1.0.5
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
