name: Continuous Integration
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 19 ] # Here, 19 (major version 63) is the latest java version currently.
      fail-fast: true
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: gradle/wrapper-validation-action@v1.0.6
      - uses: actions/setup-java@v3.10.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
