name: Continuous Integration
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        java: [ 17 ]
    #      fail-fast: true
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: gradle/actions/wrapper-validation@v3.5.0
      - uses: actions/setup-java@v4.4.0
        with:
          java-version: 21 # ${{ matrix.java }}
          distribution: 'adopt'
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
